
spring:
  security:
    jwt: ${jwt.secret}
    access: ${jwt.access-hour}
    refresh: ${jwt.refresh-week}
  datasource:
    url: ${database.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      format-sql: true
  config:
    import: classpath:tomato-db.yml, classpath:jwt-config.yml
