
spring:
  mail:
    host: ${gmail.host}
    port: ${gmail.port}
    username: ${gmail.username}
    password: ${gmail.password}
    properties:
      mail:
        smtp:
          auth: true             # SMTP 서버 인증 사용 여부 (true로 설정해야 로그인 필요)
          timeout: 5000          # SMTP 연결 타임아웃 시간 (ms 단위)
          starttls:
            enable: true         # STARTTLS 명령어를 통해 보안 연결(TLS) 사용 여부
  security:
    jwt: ${jwt.secret}
    access: ${jwt.access-hour}
    refresh: ${jwt.refresh-week}
  datasource:
    url: ${database.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      format-sql: true
  config:
    import: classpath:tomato-db.yml, classpath:jwt-config.yml, classpath:mail.yml



#logging:
#  level:
#    root: info
#    org.springframework.web.socket: debug
#    org.springframework.messaging: debug
#    org.springframework.web.socket.messaging.StompSubProtocolHandler: debug
#    org.springframework.web.socket.server.support: debug
#    org.springframework.web.socket.sockjs: debug
#    org.springframework.messaging.simp: DEBUG
#    org.springframework.messaging.simp.user: TRACE
#    org.springframework.messaging.simp.broker: TRACE
#    org.springframework.security: DEBUG
#
#
#
#logging:
#  level:
#    root: info
#    org.springframework.web.socket: debug
#    org.springframework.messaging: debug
#    org.springframework.web.socket.messaging.StompSubProtocolHandler: debug
#    org.springframework.web.socket.server.support: debug
#    org.springframework.web.socket.sockjs: debug
#    org.springframework.messaging.simp: DEBUG
#    org.springframework.messaging.simp.user: TRACE
#    org.springframework.messaging.simp.broker: TRACE
#    org.springframework.security: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE